
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1000000;


-- *** User ***
CREATE TABLE User (
  id BIGINT NOT NULL AUTO_INCREMENT,
  modificationCounter INTEGER NOT NULL,
  firstname VARCHAR (255) NULL,
  lastname VARCHAR (255) NULL,
  CONSTRAINT PK_User PRIMARY KEY(id)
);

