
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 10;

CREATE TABLE hello_user
(
  id BIGSERIAL,
  modificationCounter INTEGER DEFAULT 0,
  firstname VARCHAR (255) NOT NULL,
  lastname VARCHAR (255) NOT NULL,
  CONSTRAINT PK_Product PRIMARY KEY(id)
);
